name: Get Branch Name

on:
  push:
    branches:
      - '*'

jobs:
  get_branch_name:
    runs-on: ubuntu-latest
    env:
      RUNTIME_ENV: 'hello'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get branch name
        run: |
          echo "The current branch is ${{ github.ref }}"
          echo "RUNTIME ENV = $RUNTIME_ENV"
          export RUNTIME_ENV="HELLOWORLD!"
          echo "RUNTIME ENV = $RUNTIME_ENV"
          
      - name: Echo Changed Runtime Env
        run: |
          echo "CHANGED RUNTIME ENV = $RUNTIME_ENV"
